### ISSUE TITLE
Godo package no longer exists at specified path

### ISSUE THREAD

**Issue by Integralist** [mgutz/minimist#1]
I've recently switched to the Glide dependency and it's breaking because it's trying to locate a nested dependency of: `github.com/mgutz/godo/v1`

I've found the line that imports this dependency here: 

https://github.com/mgutz/minimist/blob/e3e5af13ccefb15bcf80187ae6879fcc99984fc9/tasks/Godofile.go#L3

This package should be updated to reflect that the package no longer exists at this location

**Comment by mgutz** [comment]
Removed godo requirement as it didn't do much other than run `go test`.

**Comment by Integralist** [comment]
Ah apologies. It seems Glide somehow picked up a version of this repo that wasn't master? I can see in master the task folder is removed
